version: '2'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    privileged: true
    volumes:
      - "./src:/var/www/html"
      - "./web_config:/etc/nginx/conf.d/"
    depends_on:
      - php-fpm
  php-fpm:
    build: ./
    ports:
      - "9000"
    privileged: true
    volumes:
      - "./src:/var/www/html"
    depends_on:
      - redis-server
  redis-server:
    image: redis:alpine
    ports:
     - 6379
    privileged: true
    volumes:
      - ./redis-data/:/data
    command: /bin/sh -c "echo 511>/proc/sys/net/core/somaxconn&&echo 'net.core.somaxconn = 2048'>>/etc/sysctl.conf&&echo 'vm.overcommit_memory = 1'>>/etc/sysctl.conf&&echo 'never'>/sys/kernel/mm/transparent_hugepage/enabled&&sysctl -p&&redis-server"
